### ISSUE TITLE
Post: poster_id needs to be updated

### ISSUE THREAD

**Issue by ivanb7** [bibanon/py8chan#11]
Return the actual poster_id from 8chan instead of error

```
# (May Change) 8chan/vichan does not use administrative IDs
    @property
    def poster_id(self):
        raise AttributeError( "'py8chan.Post' object has no attribute 'poster_id'" )
```
![image](https://user-images.githubusercontent.com/16981596/49595137-5d68a980-f945-11e8-8759-1c7b8d52e168.png)

**Comment by antonizoon** [comment]
Do they use this property in the infinity/vichan API? If so, what for?

**Comment by ivanb7** [comment]
I'm assuming its supposed to return the id of a poster. 8chan uses it.
![image](https://user-images.githubusercontent.com/16981596/49595988-4d51c980-f947-11e8-88bc-b7b1e56ce825.png)

I found a fix for it. 
It was trying to look for data.get('poster_id'), 
When it actually needs data.get('id') 

FIX:
In **post.py**
```
    # (May Change) 8chan/vichan does not use administrative IDs
    @property
    def poster_id(self):
        if self._data.get('id') is not None:
            return self._data.get('id')
        else:
            raise AttributeError("'py8chan.Post' object has no attribute 'poster_id'")
```

![image](https://user-images.githubusercontent.com/16981596/49596500-745ccb00-f948-11e8-8c68-a078fe872545.png)

**Comment by ivanb7** [comment]
Also, for 
### post.url
```
@property
    def url(self):
        return '%s#p%i' % (self._thread.url, self.post_number)
```
returns a url of the form ```https://8ch.net/<board>/res/<thread_id>.html#p<post_id>```

Should be:
```
@property
    def url(self):
        return '%s#%i' % (self._thread.url, self.post_number)
```
url should be ```https://8ch.net/<board>/res/<thread_id>.html#<post_id>```
There is not "p" after the "#"

**Comment by antonizoon** [comment]
From what I know, poster_id is used for administrative IDs on 4chan. I don't remember how the 4chan API handles user IDs like on /b/ so you may need to look that up there so we ensure consistency (maybe it's also just id)

**Comment by antonizoon** [comment]
Also, most of the changes are good feel free to make a pull request which makes ir easy for me to merge the changes.

**Comment by antonizoon** [comment]
btw you never made a pull request for these changes. If you still want to send them in just make a pull request sometime.
