### ISSUE TITLE
Allow private boards

### ISSUE THREAD

**Issue by alex-p-fisher** [bibanon/py8chan#19]
https://8kun.top/qresearch/index.html is not present in the board listing (by design):

```
py8chan.get_all_boards()
```

But the thread endpoints are still accessible if the url board name is modified:

```
board._url._board = "qresearch"
threads = board.get_thread(10550187)
threads = board.get_threads()
```

Is there any way we can add a constructor for private boards that doesn't require board metadata to be retrieved as it's not necessary for my use case?
https://github.com/bibanon/py8chan/blob/1c61cefb6fa19afa9ca89d46d7124baab22c2f1a/py8chan/board.py#L111

**Comment by antonizoon** [comment]
If you had a pull request to submit and have tested well by this point, please drop that in.

**Comment by KebabLord** [comment]
>Is there any way we can add a constructor for private boards that doesn't require board metadata to be retrieved as it's not necessary for my use case?

dunno why OP decided to access the board from `.get_all_boards()` instead of just using `.board("qresearch")`  
this constructor already exists and will work even if the board tag is set to private.
