### ISSUE TITLE
JSON Decode Error

### ISSUE THREAD

**Issue by formerlychucks14** [bibanon/py8chan#23]
Whenever I try to run my code, I get this error.

`raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

I believe this may be a probably with the API. I'm hoping someone could fix it if this API is still alive.

**Comment by KebabLord** [comment]
Can you please send your code so we can help you? :D

**Comment by formerlychucks14** [comment]
Yes here's my code.

`import py8chan

py8chan.Board("v")`

**Comment by KebabLord** [comment]
works fine on me,
```
>>> x = py8chan.Board("v")
>>> x.title                                                'Video Games'                                              >>> x.subtitle
'Vidya Gaems'
```
are you sure that you installed the requirements by pip? What python version ur using also? I can verifiy that it currently works on both 3.7 and 3.9

**Comment by KebabLord** [comment]
closing the issue due to inactivity,
the issue was probably occured because script couldn't reach the site at that time.
