### ISSUE TITLE
How to download all the images from a specific 8chan board?

### ISSUE THREAD

**Issue by sleepingcat4** [bibanon/py8chan#25]
I am bit confused how the images are accessed from a 8chan board through the API. Can you tell, how can I download all the images from a board? [for 8chan]

**Comment by KebabLord** [comment]
py8chan doesn't download the files for you, instead it parses the boards and threads to retrieve media urls.
After that you can create your own implementation of downloading or you can simply use [wget](https://www.gnu.org/software/wget/)

please check the examples:

This one will list all media urls from the first thread on /v/:
https://github.com/bibanon/py8chan/blob/bc498f3da434538676172e4b6f4413a0b105639d/examples/example5-allfiles.py#L7-L14

Here you can see how to download all files from a specific thread using the example2.py + linux commands  is specified here:
https://github.com/bibanon/py8chan/blob/bc498f3da434538676172e4b6f4413a0b105639d/examples/example2.py#L9

Here is a simple approach i wrote that downloads all files from a board:
```py
import requests, py8chan
board = py8chan.Board('v')
all_thread_ids = board.get_all_thread_ids()
for thread_id in all_thread_ids:
    thread = board.get_thread(thread_id)
    for file_url in thread.files():
        filename = file_url.split("/")[-1]
        res = requests.get(file_url)
        with open(filename,"wb") as fp:
            fp.write(res.content)
        print("Downloaded: " + file_url)
```

Here is a better approach that downloads all files with original names using "wget" tool on linux in OOP way:
```py
import py8chan, os
board = py8chan.Board('v')
all_threads = board.get_all_threads()
for thread in all_threads:
    for file in thread.file_objects():
        os.system(f"wget {file.file_url} -O {file.filename_original}")
        print("Downloaded: " + file.filename_original)
```

**Comment by sleepingcat4** [comment]
thank you for the help. Can you tell, how it can be possible to download all the threads and their data of a specific board? I tried a few methods but was unsuccessful @KebabLord

**Comment by KebabLord** [comment]
> Can you tell, how it can be possible to download all the threads and their data of a specific board? I tried a few methods but was unsuccessful @KebabLord 

what do you mean by "all data"? The two code pieces i provided above already downloads all the media such as images,videos from all threads in a board (it's set to /v/ in the examples i provided). You can use one of them.

do you also want to dump the texts along with those media? If so, you should either create your own archiver implementation or use another application. This repo is basically a python wrapper for the 8chan api. It's not a downloader nor archiver.

this repo is basically the python wrapper of 8chan's api, it doesn't directly allow you to download

**Comment by KebabLord** [comment]
I'm closing this issue since i think my last answers were enough and i already created a basic implementation for you that downloads all the media from a board. If you want to know further, just check the examples or read the codes.
