### ISSUE TITLE
Last-modified header supplanted by JSON value

### ISSUE THREAD

**Issue by antonizoon** [bibanon/py8chan#4]
Instead of Last-modified being in the HTTP header like on 4chan, it is emitted as a JSON value in the 8chan API.

http://8ch.net/v/res/10039522.json

_from_requests() needs to be modified to accept this.

**Comment by Amersel** [comment]
Solved by https://github.com/bibanon/py8chan/commit/c2cf66ff80fceb590e666f5968baae201fe79c25
